# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: projeto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprojeto.proto\"E\n\x0cHelloRequest\x12\x0e\n\x06\x63id_id\x18\x01 \x01(\x03\x12\x12\n\ntitle_task\x18\x02 \x01(\t\x12\x11\n\tdesc_task\x18\x03 \x01(\t\"2\n\nHelloReply\x12\x0e\n\x06\x63id_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x64\x61\x64os_client\x18\x02 \x01(\t2\xfc\x03\n\x07Greeter\x12#\n\x03set\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12#\n\x03get\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12&\n\x06\x64\x65lete\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12.\n\x0einserirCliente\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x30\n\x10modificarCliente\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x30\n\x10recuperarCliente\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12-\n\rapagarCliente\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12-\n\rinserirTarefa\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12/\n\x0fmodificarTarefa\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12-\n\rlistarTarefas\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12-\n\rapagarTarefas\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'projeto_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'projeto_pb2'
  # @@protoc_insertion_point(class_scope:HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=17
  _HELLOREQUEST._serialized_end=86
  _HELLOREPLY._serialized_start=88
  _HELLOREPLY._serialized_end=138
  _GREETER._serialized_start=141
  _GREETER._serialized_end=649
# @@protoc_insertion_point(module_scope)
